import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Timmer from '../components/timmer'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Timmer App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Timmer App</h1>
        <Timmer />
      </main>
    </div>
  )
}

export default Home
